#############################################################################
# Makefile for building: dip2
# Generated by qmake (2.01a) (Qt 4.8.6) on: Sat Jan 10 08:49:25 2015
# Project:  dip2.pro
# Template: app
# Command: /usr/lib/i386-linux-gnu/qt4/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile dip2.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_XMLPATTERNS_LIB -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtXmlPatterns -I/usr/include/qt4 -I. -Iwidgets -Igrid -Ifield -Ipostfix -Iinfix -Ipoligonization -Iicons -I/usr/X11R6/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -L/usr/X11R6/lib -lglut -lGLU infix/infixlex.o -lQtXmlPatterns -lQtOpenGL -lQtGui -lQtCore -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/i386-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		field/field.cpp \
		field/fieldobject.cpp \
		field/metaobject.cpp \
		grid/grid.cpp \
		poligonization/gridcell.cpp \
		poligonization/normalization.cpp \
		poligonization/poligonizator.cpp \
		postfix/postfixexpr.cpp \
		postfix/postfixtoken.cpp \
		postfix/variablesmanager.cpp \
		widgets/glarea.cpp \
		widgets/mainwindow.cpp \
		widgets/metaobjectscontroller.cpp \
		widgets/viewcontroller.cpp moc_variablesmanager.cpp \
		moc_glarea.cpp \
		moc_mainwindow.cpp \
		moc_metaobjectscontroller.cpp \
		moc_viewcontroller.cpp
OBJECTS       = main.o \
		field.o \
		fieldobject.o \
		metaobject.o \
		grid.o \
		gridcell.o \
		normalization.o \
		poligonizator.o \
		postfixexpr.o \
		postfixtoken.o \
		variablesmanager.o \
		glarea.o \
		mainwindow.o \
		metaobjectscontroller.o \
		viewcontroller.o \
		moc_variablesmanager.o \
		moc_glarea.o \
		moc_mainwindow.o \
		moc_metaobjectscontroller.o \
		moc_viewcontroller.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		dip2.pro
QMAKE_TARGET  = dip2
DESTDIR       = 
TARGET        = dip2

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_metaobjectscontroller.h ui_viewcontroller.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: dip2.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtXmlPatterns.prl \
		/usr/lib/i386-linux-gnu/libQtOpenGL.prl \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile dip2.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/opengl.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtXmlPatterns.prl:
/usr/lib/i386-linux-gnu/libQtOpenGL.prl:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile dip2.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/dip21.0.0 || $(MKDIR) .tmp/dip21.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/dip21.0.0/ && $(COPY_FILE) --parents field/field.h field/fieldobject.h field/metaobject.h grid/grid.h grid/space_types.h infix/infixlex_types.h poligonization/gridcell.h poligonization/marchingcubes_tables.h poligonization/normalization.h poligonization/poligonizator.h postfix/postfixexpr.h postfix/postfixtoken.h postfix/variablesmanager.h widgets/glarea.h widgets/mainwindow.h widgets/metaobjectscontroller.h widgets/viewcontroller.h infix/infixlex_funcs.c .tmp/dip21.0.0/ && $(COPY_FILE) --parents main.cpp field/field.cpp field/fieldobject.cpp field/metaobject.cpp grid/grid.cpp poligonization/gridcell.cpp poligonization/normalization.cpp poligonization/poligonizator.cpp postfix/postfixexpr.cpp postfix/postfixtoken.cpp postfix/variablesmanager.cpp widgets/glarea.cpp widgets/mainwindow.cpp widgets/metaobjectscontroller.cpp widgets/viewcontroller.cpp .tmp/dip21.0.0/ && $(COPY_FILE) --parents widgets/mainwindow.ui widgets/metaobjectscontroller.ui widgets/viewcontroller.ui .tmp/dip21.0.0/ && (cd `dirname .tmp/dip21.0.0` && $(TAR) dip21.0.0.tar dip21.0.0 && $(COMPRESS) dip21.0.0.tar) && $(MOVE) `dirname .tmp/dip21.0.0`/dip21.0.0.tar.gz . && $(DEL_FILE) -r .tmp/dip21.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_variablesmanager.cpp moc_glarea.cpp moc_mainwindow.cpp moc_metaobjectscontroller.cpp moc_viewcontroller.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_variablesmanager.cpp moc_glarea.cpp moc_mainwindow.cpp moc_metaobjectscontroller.cpp moc_viewcontroller.cpp
moc_variablesmanager.cpp: postfix/variablesmanager.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) postfix/variablesmanager.h -o moc_variablesmanager.cpp

moc_glarea.cpp: grid/space_types.h \
		field/field.h \
		field/metaobject.h \
		field/fieldobject.h \
		grid/grid.h \
		postfix/variablesmanager.h \
		postfix/postfixexpr.h \
		infix/infixlex_types.h \
		widgets/glarea.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) widgets/glarea.h -o moc_glarea.cpp

moc_mainwindow.cpp: ui_mainwindow.h \
		widgets/glarea.h \
		grid/space_types.h \
		field/field.h \
		field/metaobject.h \
		field/fieldobject.h \
		grid/grid.h \
		postfix/variablesmanager.h \
		postfix/postfixexpr.h \
		infix/infixlex_types.h \
		widgets/metaobjectscontroller.h \
		ui_metaobjectscontroller.h \
		poligonization/poligonizator.h \
		poligonization/gridcell.h \
		widgets/viewcontroller.h \
		ui_viewcontroller.h \
		widgets/mainwindow.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) widgets/mainwindow.h -o moc_mainwindow.cpp

moc_metaobjectscontroller.cpp: ui_metaobjectscontroller.h \
		field/field.h \
		field/metaobject.h \
		field/fieldobject.h \
		grid/grid.h \
		grid/space_types.h \
		postfix/variablesmanager.h \
		poligonization/poligonizator.h \
		poligonization/gridcell.h \
		widgets/metaobjectscontroller.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) widgets/metaobjectscontroller.h -o moc_metaobjectscontroller.cpp

moc_viewcontroller.cpp: ui_viewcontroller.h \
		widgets/viewcontroller.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) widgets/viewcontroller.h -o moc_viewcontroller.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_metaobjectscontroller.h ui_viewcontroller.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_metaobjectscontroller.h ui_viewcontroller.h
ui_mainwindow.h: widgets/mainwindow.ui \
		widgets/glarea.h \
		widgets/metaobjectscontroller.h \
		widgets/viewcontroller.h \
		grid/space_types.h \
		field/field.h \
		field/metaobject.h \
		field/fieldobject.h \
		grid/grid.h \
		postfix/variablesmanager.h \
		postfix/postfixexpr.h \
		infix/infixlex_types.h \
		ui_metaobjectscontroller.h \
		field/field.h \
		field/metaobject.h \
		field/fieldobject.h \
		grid/grid.h \
		grid/space_types.h \
		postfix/variablesmanager.h \
		poligonization/poligonizator.h \
		poligonization/gridcell.h \
		ui_viewcontroller.h
	/usr/lib/i386-linux-gnu/qt4/bin/uic widgets/mainwindow.ui -o ui_mainwindow.h

ui_metaobjectscontroller.h: widgets/metaobjectscontroller.ui
	/usr/lib/i386-linux-gnu/qt4/bin/uic widgets/metaobjectscontroller.ui -o ui_metaobjectscontroller.h

ui_viewcontroller.h: widgets/viewcontroller.ui
	/usr/lib/i386-linux-gnu/qt4/bin/uic widgets/viewcontroller.ui -o ui_viewcontroller.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp widgets/mainwindow.h \
		ui_mainwindow.h \
		widgets/glarea.h \
		grid/space_types.h \
		field/field.h \
		field/metaobject.h \
		field/fieldobject.h \
		grid/grid.h \
		postfix/variablesmanager.h \
		postfix/postfixexpr.h \
		infix/infixlex_types.h \
		widgets/metaobjectscontroller.h \
		ui_metaobjectscontroller.h \
		poligonization/poligonizator.h \
		poligonization/gridcell.h \
		widgets/viewcontroller.h \
		ui_viewcontroller.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

field.o: field/field.cpp field/field.h \
		field/metaobject.h \
		field/fieldobject.h \
		grid/grid.h \
		grid/space_types.h \
		postfix/variablesmanager.h \
		postfix/postfixexpr.h \
		infix/infixlex_types.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o field.o field/field.cpp

fieldobject.o: field/fieldobject.cpp field/fieldobject.h \
		grid/grid.h \
		grid/space_types.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fieldobject.o field/fieldobject.cpp

metaobject.o: field/metaobject.cpp grid/space_types.h \
		field/metaobject.h \
		field/fieldobject.h \
		grid/grid.h \
		postfix/variablesmanager.h \
		postfix/postfixexpr.h \
		infix/infixlex_types.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o metaobject.o field/metaobject.cpp

grid.o: grid/grid.cpp grid/grid.h \
		field/fieldobject.h \
		grid/space_types.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o grid.o grid/grid.cpp

gridcell.o: poligonization/gridcell.cpp grid/grid.h \
		poligonization/gridcell.h \
		grid/space_types.h \
		poligonization/marchingcubes_tables.h \
		poligonization/normalization.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gridcell.o poligonization/gridcell.cpp

normalization.o: poligonization/normalization.cpp poligonization/normalization.h \
		grid/space_types.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o normalization.o poligonization/normalization.cpp

poligonizator.o: poligonization/poligonizator.cpp field/fieldobject.h \
		grid/grid.h \
		grid/space_types.h \
		poligonization/poligonizator.h \
		poligonization/gridcell.h \
		poligonization/normalization.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o poligonizator.o poligonization/poligonizator.cpp

postfixexpr.o: postfix/postfixexpr.cpp infix/infixlex_types.h \
		postfix/postfixtoken.h \
		postfix/postfixexpr.h \
		postfix/variablesmanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o postfixexpr.o postfix/postfixexpr.cpp

postfixtoken.o: postfix/postfixtoken.cpp postfix/postfixtoken.h \
		infix/infixlex_types.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o postfixtoken.o postfix/postfixtoken.cpp

variablesmanager.o: postfix/variablesmanager.cpp postfix/variablesmanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o variablesmanager.o postfix/variablesmanager.cpp

glarea.o: widgets/glarea.cpp widgets/glarea.h \
		grid/space_types.h \
		field/field.h \
		field/metaobject.h \
		field/fieldobject.h \
		grid/grid.h \
		postfix/variablesmanager.h \
		postfix/postfixexpr.h \
		infix/infixlex_types.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o glarea.o widgets/glarea.cpp

mainwindow.o: widgets/mainwindow.cpp widgets/mainwindow.h \
		ui_mainwindow.h \
		widgets/glarea.h \
		grid/space_types.h \
		field/field.h \
		field/metaobject.h \
		field/fieldobject.h \
		grid/grid.h \
		postfix/variablesmanager.h \
		postfix/postfixexpr.h \
		infix/infixlex_types.h \
		widgets/metaobjectscontroller.h \
		ui_metaobjectscontroller.h \
		poligonization/poligonizator.h \
		poligonization/gridcell.h \
		widgets/viewcontroller.h \
		ui_viewcontroller.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o widgets/mainwindow.cpp

metaobjectscontroller.o: widgets/metaobjectscontroller.cpp widgets/metaobjectscontroller.h \
		ui_metaobjectscontroller.h \
		field/field.h \
		field/metaobject.h \
		field/fieldobject.h \
		grid/grid.h \
		grid/space_types.h \
		postfix/variablesmanager.h \
		poligonization/poligonizator.h \
		poligonization/gridcell.h \
		widgets/glarea.h \
		postfix/postfixexpr.h \
		infix/infixlex_types.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o metaobjectscontroller.o widgets/metaobjectscontroller.cpp

viewcontroller.o: widgets/viewcontroller.cpp widgets/viewcontroller.h \
		ui_viewcontroller.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o viewcontroller.o widgets/viewcontroller.cpp

moc_variablesmanager.o: moc_variablesmanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_variablesmanager.o moc_variablesmanager.cpp

moc_glarea.o: moc_glarea.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_glarea.o moc_glarea.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_metaobjectscontroller.o: moc_metaobjectscontroller.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_metaobjectscontroller.o moc_metaobjectscontroller.cpp

moc_viewcontroller.o: moc_viewcontroller.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_viewcontroller.o moc_viewcontroller.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

